FROM python:3.7
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN apt-get update && apt-get -y install nginx
RUN mkdir -p /code/static
RUN mkdir -p /code/media
WORKDIR /code
COPY . /code/
COPY ./etc/nginx.conf /etc/nginx/nginx.conf
RUN pip install -r requirements.txt
ENTRYPOINT ["/code/etc/entrypoint_prod.sh"]