FROM python:3.7
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN apt-get update && apt-get -y install nginx

RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash
RUN apt-get -y install nodejs
RUN npm install -g yarn

RUN mkdir -p /code/static
RUN mkdir -p /code/media
WORKDIR /code
COPY . /code/
COPY ./etc/nginx.conf /etc/nginx/nginx.conf

ENV PATH /code/frontend/node_modules/.bin:$PATH
COPY frontend/package.json ./
RUN cd frontend && npm install --silent
RUN cd frontend && npm install react-scripts@3.4.3 -g --silent
RUN cd frontend && yarn build
RUN rm -rf /usr/share/nginx/html/*
RUN cp -avr /code/frontend/build /usr/share/nginx/html

RUN pip install -r requirements.txt
ENTRYPOINT ["/code/etc/entrypoint_prod.sh"]